### ISSUE TITLE
Logon background is low-res on certain resolutions

### ISSUE THREAD

**Issue by aliasmaychange** [wiktorwiktor12/ConsoleLogonHook#26]
Hello, I have a 1920x1080 screen, and despite the fact that a 1920x1200 picture is available in ConsoleLogonUI.dll (as seen in ResourceHacker), it appears to use the 1440x900 resource. If it's any assistance, I use Windows 10 IoT Enterprise LTSC 2021.

**Comment by wiktorwiktor12** [comment]
thats intended, the 1920x1200 image would only be used for 16:10 monitors, you can verify this by testing it out on actual 7 since the 1920x1200 image has a unique mark on the right, the low resolution look is something i don't know why it exactly occurs, but its likely due a to change in how dui handles images, i may in the future work on upscaling it before passing the image to dui to render.

**Comment by wiktorwiktor12** [comment]
for now, if u want a higher resolution image, you can override it using a windows 7 logon screen background changer app

**Comment by aliasmaychange** [comment]
Ah, I thought that was a bug.
